#!/bin/bash
# Set the region
REGION="eu-north-1"

# Create a VPC
VPC_ID=$(aws ec2 create-vpc --cidr-block 172.1.0.0/16 --region $REGION --tag-specifications "ResourceType=vpc,Tags=[{Key=Name,Value=test}]" --query Vpc.VpcId --output text)
echo "VPC created with ID: $VPC_ID"

# Create an Internet Gateway (IGW)
IGW_ID=$(aws ec2 create-internet-gateway --region $REGION --tag-specifications "ResourceType=internet-gateway,Tags=[{Key=Name,Value=test-igw}]" --query InternetGateway.InternetGatewayId --output text)
echo "Internet Gateway created with ID: $IGW_ID"

# Attach the IGW to the VPC
aws ec2 attach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID --region $REGION
echo "Internet Gateway $IGW_ID attached to VPC $VPC_ID"

# Create a new subnet in the VPC
SUBNET_ID=$(aws ec2 create-subnet --vpc-id $VPC_ID --cidr-block 172.1.1.0/24 --region $REGION --tag-specifications "ResourceType=subnet,Tags=[{Key=Name,Value=test-subnet}]" --query Subnet.SubnetId --output text)
echo "Subnet created with ID: $SUBNET_ID"

# Explicitly associate subnet with a route table
# First, get the route table ID for the VPC
RTB_ID=$(aws ec2 describe-route-tables --filters "Name=vpc-id,Values=$VPC_ID" --query "RouteTables[0].RouteTableId" --region $REGION --output text)
echo "Route Table ID: $RTB_ID"

# Associate the subnet with the route table
aws ec2 associate-route-table --route-table-id $RTB_ID --subnet-id $SUBNET_ID --region $REGION
echo "Subnet $SUBNET_ID associated with Route Table $RTB_ID"

# Add a route for our route table to the IGW
aws ec2 create-route --route-table-id $RTB_ID --destination-cidr-block 0.0.0.0/0 --gateway-id $IGW_ID --region $REGION
echo "Route added to Route Table $RTB_ID for Internet Gateway $IGW_ID"
