AWSTemplateFormatVersion: "2010-09-09"
Description: Simple S3 bucket creator

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain # Retains the bucket even after stack deletion
    Properties:
      AccessControl: Private # Ensures the bucket is private
      # CloudFormation will automatically create a unique name for the bucket

Outputs:
  BucketName:
    Description: "Name of the S3 bucket"
    Value: !Ref S3Bucket
