AWSTemplateFormatVersion : "2010-09-09"
Description : Simple s3 bucket creator 
Resources:
  S3Bucket:
    #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    #commented below to create a bucket with a random name
    #Properties:
      #BucketName: DOC-EXAMPLE-BUCKET